/*---------------------------------------------------------------------------*/
/* drwfigur.h                                                                */
/*                                                                           */
/* function prototypes.                                                      */
/*---------------------------------------------------------------------------*/
unsigned long * getFigure(long lFigure, unsigned long *ulSize, int *iType);
