/*------------------------------------------------------------------------*/
/*  Name: drwfile.h                                                       */
/*                                                                        */
/*  Description : Function for loading the drawit file.                   */
/*------------------------------------------------------------------------*/
BOOL LoadDrwFile(pLoadinfo pli,WINDOWINFO *pwi);
