/*------------------------------------------------------------------------*/
/*  Name: drwpic.h                                                        */
/*                                                                        */
/*  Description : Converts a lotus pic file to an OS/2 Metafile.          */
/*                                                                        */
/*                                                                        */
/*------------------------------------------------------------------------*/
BOOL picLoad(WINDOWINFO *pwi);

